/* Optional local publishing helper. Never transmits or serializes a key. */
(function(root,factory){
  const api=factory();
  if(typeof module==='object'&&module.exports)module.exports=api;
  else {root.AIDailyMobileUpdate=api;api.install();}
})(typeof window==='undefined'?globalThis:window,function(){
  'use strict';
  const encoder=new TextEncoder();
  const clone=x=>JSON.parse(JSON.stringify(x));
  const assert=(ok,msg)=>{if(!ok)throw new Error(msg);};
  const encode=x=>encoder.encode(JSON.stringify(x));
  function validate(p,b){
    assert(p&&p.format==='ai-daily-private-update-v1','請選擇今次提供嘅更新檔。');
    assert(/^\d{4}-\d{2}-\d{2}$/.test(p.date)&&p.date>p.base_date,'更新日期無效。');
    assert(b.latest.date===p.base_date&&b.sha256===p.base_sha256,'原 App 資料已改變，需要重新準備更新檔。');
    const d=p.payload;
    assert(d.date===p.date&&d.usize===255&&d.earn.calendar_ok===true&&!d.miss.length,'更新資料未通過檢查。');
    assert(d.picks.date===p.date&&['正常','減注','停手'].includes(d.picks.regime.gate),'作戰卡日期或狀態無效。');
    assert(d.layerBars.meta.asof===p.date,'層指數日期不一致。');
    const members=Object.values(d.members).flat().map(m=>m.t);
    assert(members.length===255&&new Set(members).size===255&&Object.keys(d.members).length===9,'股票名單不完整。');
    assert(Object.keys(p.charts).sort().join()===members.slice().sort().join(),'圖表名單不完整。');
    const day=p.date.slice(5).replace('-','/');
    for(const t of members){
      const c=p.charts[t];
      assert(/^[A-Z0-9.-]+$/.test(t)&&c.t===t&&c.dates.at(-1)===day&&c.ohlc.length===c.dates.length,'圖表日期或格式無效。');
    }
    assert(Array.isArray(b.history)&&Array.isArray(b.manifest.dates),'歷史資料無法確認。');
    assert(p.history_record.date===p.date,'歷史記錄日期不一致。');
    const s=b.series,n=s.dates.length;
    assert(n>0&&!s.dates.includes(day),'趨勢資料已包含本次日期。');
    for(const k of ['capsw','adv','up4','dn4','gapn','gapwin','gapmed','spy','qqq'])
      assert(Array.isArray(s[k])&&s[k].length===n&&p.series_record[k]!==undefined,'趨勢資料不完整。');
    // The original publisher appends MA values without requiring the legacy
    // arrays to have the date array's length. Preserve those arrays verbatim;
    // rejecting unequal lengths prevents valid existing Apps from updating.
    for(const type of ['spy_ma','qqq_ma'])for(const k of ['m20','m50','m200']){
      assert(Array.isArray(s[type]?.[k]),'原有均線格式無效：'+type+'/'+k+'。');
      assert(p.series_record[type]?.[k]!==undefined,'更新檔缺少均線：'+type+'/'+k+'。');
    }
    return members;
  }
  async function createFiles(p,b,readKey,c,progress=()=>{}){
    const members=validate(p,b),d=p.payload,day=p.date.slice(5).replace('-','/'),tag=p.date.replaceAll('-','');
    const history=clone(b.history).filter(h=>h.date!==p.date);
    history.push(p.history_record);history.sort((a,z)=>a.date.localeCompare(z.date));
    const ser=clone(b.series);ser.dates.push(day);
    for(const k of ['capsw','adv','up4','dn4','gapn','gapwin','gapmed','spy','qqq'])ser[k].push(p.series_record[k]);
    for(const type of ['spy_ma','qqq_ma'])for(const k of ['m20','m50','m200'])ser[type][k].push(p.series_record[type][k]);
    ser.tagix={};
    for(const [name,values]of Object.entries(p.indices)){
      const line=ser.dates.map(date=>values[date]??null);
      if(name==='__capix')ser.capix=line;else if(name==='__swix')ser.swix=line;else ser.tagix[name]=line;
    }
    const manifest=clone(b.manifest);
    manifest.dates=[...new Set([...manifest.dates,tag])].sort().slice(-60);manifest.updated=p.date;
    // The App already holds an extractable decrypt-only CryptoKey. Reimport it
    // in this device's memory for encryption. No password or raw key leaves here.
    const material=new Uint8Array(await c.subtle.exportKey('raw',readKey));
    let key;
    try{key=await c.subtle.importKey('raw',material,'AES-GCM',false,['encrypt','decrypt']);}
    finally{material.fill(0);}
    const encrypt=async obj=>{
      const iv=c.getRandomValues(new Uint8Array(12));
      const plain=encode(obj),body=new Uint8Array(await c.subtle.encrypt({name:'AES-GCM',iv},key,plain));
      const result=new Uint8Array(12+body.length);result.set(iv);result.set(body,12);
      // Verify generated bytes against the same local key before exporting.
      const check=new Uint8Array(await c.subtle.decrypt({name:'AES-GCM',iv},key,body));
      assert(check.length===plain.length&&check.every((v,i)=>v===plain[i]),'加密檔驗證失敗。');
      return result;
    };
    const files={'manifest.json':encode(manifest)};
    files['latest.enc']=await encrypt(d);files['data/'+tag+'.enc']=files['latest.enc'];
    files['history.enc']=await encrypt(history.slice(-120));files['series.enc']=await encrypt(ser);
    let count=0;
    for(const t of members){files['charts/'+t+'.enc']=await encrypt(p.charts[t]);progress(++count,members.length);}
    assert(Object.keys(files).length===260,'更新檔數量不正確。');
    return files;
  }
  // Small ZIP writer (stored entries) keeps the phone path dependency-free.
  const table=Array.from({length:256},(_,n)=>{for(let j=0;j<8;j++)n=(n&1)?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
  function crc32(bytes){let n=0xffffffff;for(const b of bytes)n=table[(n^b)&255]^(n>>>8);return(n^0xffffffff)>>>0;}
  function zip(files){
    const chunks=[],central=[];let offset=0,centralSize=0;
    for(const name of Object.keys(files).sort()){
      assert(/^(latest|history|series)\.enc$|^manifest\.json$|^data\/\d{8}\.enc$|^charts\/[A-Z0-9.-]+\.enc$/.test(name),'不允許匯出此檔案。');
      const bytes=files[name],nm=encoder.encode(name),crc=crc32(bytes);
      const h=new Uint8Array(30+nm.length),v=new DataView(h.buffer);
      v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(12,33,true);
      v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,nm.length,true);h.set(nm,30);
      const q=new Uint8Array(46+nm.length),w=new DataView(q.buffer);
      w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(14,33,true);
      w.setUint32(16,crc,true);w.setUint32(20,bytes.length,true);w.setUint32(24,bytes.length,true);w.setUint16(28,nm.length,true);w.setUint32(42,offset,true);q.set(nm,46);
      chunks.push(h,bytes);central.push(q);offset+=h.length+bytes.length;centralSize+=q.length;
    }
    const end=new Uint8Array(22),e=new DataView(end.buffer);
    e.setUint32(0,0x06054b50,true);e.setUint16(8,central.length,true);e.setUint16(10,central.length,true);
    e.setUint32(12,centralSize,true);e.setUint32(16,offset,true);
    const out=new Uint8Array(offset+centralSize+end.length);let pos=0;
    for(const part of [...chunks,...central,end]){out.set(part,pos);pos+=part.length;}
    return out;
  }
  function install(){
    const host=document.getElementById('app');if(!host)return;
    const box=document.createElement('details');box.className='card';box.id='mobile-update';
    box.innerHTML='<summary>更新資料</summary><p class="lab">選取今次提供嘅更新檔，再將產生嘅加密 ZIP 交返 ChatGPT 完成發布。解鎖金鑰會留喺本機。</p><input type="file" accept=".json,application/json" aria-label="選擇更新檔"><p class="lab" data-selected>尚未選擇更新檔。</p><p class="lab" role="status"></p><button type="button" hidden>重新處理已選檔</button><a hidden download>下載加密 ZIP</a><p class="lab">更新工具 v1.1</p>';
    host.appendChild(box);
    const input=box.querySelector('input'),selected=box.querySelector('[data-selected]'),status=box.querySelector('[role="status"]'),retry=box.querySelector('button'),link=box.querySelector('a');let url=null;
    const processFile=async()=>{
      if(url){URL.revokeObjectURL(url);url=null;}link.hidden=true;
      const file=input.files[0];if(!file)return;
      selected.textContent='已選擇：'+file.name;
      input.disabled=true;retry.hidden=true;
      try{
        assert(typeof KEY!=='undefined'&&KEY,'請用已經自動解鎖嘅手機 App。');
        assert(file.size<25*1024*1024,'更新檔太大。');status.textContent='檢查更新檔…';
        const p=JSON.parse(await file.text());
        const fetchBytes=async path=>{const r=await fetch(path+'?t='+Date.now(),{cache:'no-store'});assert(r.ok,'原資料暫時讀取唔到，請稍後再試。');return r.arrayBuffer();};
        const latestBytes=await fetchBytes('latest.enc');
        const hash=new Uint8Array(await crypto.subtle.digest('SHA-256',latestBytes));
        const sha256=Array.from(hash,x=>x.toString(16).padStart(2,'0')).join('');
        const response=await fetch('manifest.json?t='+Date.now(),{cache:'no-store'});assert(response.ok,'日期清單讀取失敗。');
        const b={latest:await dec(latestBytes),history:await dec(await fetchBytes('history.enc')),series:await dec(await fetchBytes('series.enc')),manifest:await response.json(),sha256};
        const files=await createFiles(p,b,KEY,crypto,(done,total)=>{status.textContent='正在本機加密圖表 '+done+'/'+total+'…';});
        url=URL.createObjectURL(new Blob([zip(files)],{type:'application/zip'}));
        link.href=url;link.download='ai-daily-'+p.date.replaceAll('-','')+'-encrypted.zip';link.textContent='下載 '+p.date+' 加密 ZIP';link.hidden=false;
        status.textContent='260 個檔案已驗證。下載 ZIP 後傳返呢段 ChatGPT 對話，先會正式發布。';
      }catch(error){status.textContent=error instanceof SyntaxError?'呢個檔案格式唔正確。':error.message;retry.hidden=false;}
      finally{input.disabled=false;}
    };
    input.addEventListener('change',processFile);
    retry.addEventListener('click',processFile);
  }
  return {validate,createFiles,zip,install};
});
